import { BUILT_IN_RATES_DATE, CURRENCY_TABLE } from './currencyTable';

export interface CurrencyDef {
  code: string;
  symbolAr: string;
  symbolEn: string;
  nameAr: string;
  nameEn: string;
  /**
   * Built-in rate: the value of 1 unit of this currency in SAR (the base), as of
   * BUILT_IN_RATES_DATE. Only a fallback — CurrencyContext converts with downloaded
   * rates once the device has them (FEATURE_SPEC 0.5).
   */
  rate: number;
}

/**
 * Every currency the app offers: the original 20 first, then the rest by code.
 * Generated by `npm run currencies` (scripts/buildCurrencies.ts) — change the script, not the table.
 */
export const CURRENCIES: CurrencyDef[] = CURRENCY_TABLE;

export { BUILT_IN_RATES_DATE };

/**
 * The app's original currencies. A downloaded rate table is only accepted when it covers
 * all of them; any other currency it lacks keeps its last known rate.
 */
export const CORE_CURRENCY_CODES: readonly string[] = [
  'SAR',
  'USD',
  'EUR',
  'GBP',
  'AED',
  'KWD',
  'BHD',
  'QAR',
  'OMR',
  'EGP',
  'JOD',
  'TRY',
  'INR',
  'PKR',
  'PHP',
  'CNY',
  'JPY',
  'CAD',
  'AUD',
  'CHF',
];

export const DEFAULT_CURRENCY_CODE = 'SAR';

const BY_CODE = new Map(CURRENCIES.map((currency) => [currency.code, currency]));

/** An unknown code falls back to the base currency (SAR), as it always has. */
export function getCurrency(code: string): CurrencyDef {
  return BY_CODE.get(code) ?? CURRENCIES[0];
}
