// Curated slug allow-list for src/constants/brandIcons.ts (CLAUDE.md rule 7).
// Slugs are simple-icons' normalized `slug` field, not the `si*` export key.
// buildBrandIcons.ts filters this list against what's actually installed, so
// an icon simple-icons has removed (trademark takedowns happen) just falls
// out silently rather than breaking the build.

export const BRAND_ICON_SLUGS: string[] = [
  // Streaming & entertainment
  'netflix',
  'youtube',
  'youtubemusic',
  'youtubetv',
  'hbo',
  'hbomax',
  'appletv',
  'paramountplus',
  'crunchyroll',
  'twitch',
  'plex',
  'vimeo',
  'googletv',
  'trillertv',
  'tvtime',

  // Music
  'spotify',
  'applemusic',
  'soundcloud',
  'tidal',
  'pandora',
  'deezer',
  'neteasecloudmusic',
  'musicbrainz',

  // AI / productivity software subscriptions
  'claude',
  'anthropic',
  'notion',
  'figma',
  'canvas',
  'zoom',
  'dropbox',
  'googledrive',
  'icloud',
  'evernote',
  'grammarly',
  'quickbooks',
  'notebooklm',
  'todoist',
  'trello',
  'asana',
  'github',
  'githubcopilot',
  'linear',
  'obsidian',
  '1password',
  'lastpass',
  'nordvpn',
  'expressvpn',
  'protonvpn',
  'openvpn',
  'protonmail',
  'cloudflare',
  'alibabacloud',
  'gitbook',

  // Payments / fintech / banks
  'paypal',
  'visa',
  'mastercard',
  'americanexpress',
  'applepay',
  'googlepay',
  'stripe',
  'venmo',
  'wise',
  'revolut',
  'coinbase',
  'binance',
  'klarna',
  'alipay',
  'afterpay',
  'payoneer',
  'paysafe',
  'walletconnect',
  'contactlesspayment',
  'bankofamerica',
  'nubank',
  'starlingbank',
  'axisbank',
  'hdfcbank',
  'icicibank',

  // Telecom & utilities
  'vodafone',
  'verizon',
  'orange',
  'internetarchive',
  'privateinternetaccess',

  // Ride-hailing / delivery / travel
  'uber',
  'ubereats',
  'doordash',
  'deliveroo',
  'lyft',
  'airbnb',
  'bookingdotcom',
  'expedia',
  'ryanair',
  'hotelsdotcom',
  'hiltonhotelsandresorts',
  'americanairlines',
  'unitedairlines',
  'southwestairlines',
  'turkishairlines',
  'singaporeairlines',

  // E-commerce & retail
  'ebay',
  'etsy',
  'shopify',
  'shopee',
  'aliexpress',
  'ikea',
  'target',
  'prestashop',
  'shopware',
  'trustedshops',

  // Fitness & wellness
  'strava',
  'fitbit',
  'headspace',
  'peloton',
  'nike',

  // Gaming
  'steam',
  'playstation',
  'epicgames',
  'ea',
  'ubisoft',
  'discord',
  'roblox',
  'gamejolt',
  'riotgames',
  'heroicgameslauncher',

  // Misc subscriptions / media / social
  'audible',
  'duolingo',
  'coursera',
  'udemy',
  'futurelearn',
  'skillshare',
  'x',
  'facebook',
  'instagram',
  'snapchat',
  'tiktok',
  'pinterest',
  'reddit',
  'whatsapp',
  'telegram',
  'signal',
  'bookbub',
  'bookmyshow',
];
