// One-time build script (CLAUDE.md rule 7). Run with `npm run brandicons`.
// Reads simple-icons (dev-only dependency, never shipped at runtime) and
// writes the curated subset out as a flat, framework-agnostic data file.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import * as simpleIcons from 'simple-icons';
import { BRAND_ICON_SLUGS } from './brandIconSlugs';

interface BrandIcon {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

const bySlug = new Map<string, BrandIcon>();
for (const value of Object.values(simpleIcons)) {
  const icon = value as { slug?: string; title?: string; hex?: string; path?: string };
  if (icon && typeof icon.slug === 'string') {
    bySlug.set(icon.slug, {
      slug: icon.slug,
      title: icon.title ?? icon.slug,
      hex: icon.hex ?? '888888',
      path: icon.path ?? '',
    });
  }
}

const found: BrandIcon[] = [];
const missing: string[] = [];

for (const slug of BRAND_ICON_SLUGS) {
  const icon = bySlug.get(slug);
  if (icon) found.push(icon);
  else missing.push(slug);
}

found.sort((a, b) => a.slug.localeCompare(b.slug));

const header = `// AUTO-GENERATED by scripts/buildBrandIcons.ts — do not edit by hand.
// Regenerate with \`npm run brandicons\` after editing scripts/brandIconSlugs.ts.
// See CLAUDE.md rule 7.

export interface BrandIcon {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

export const BRAND_ICONS: BrandIcon[] = ${JSON.stringify(found, null, 2)};

export function findBrandIcon(query: string): BrandIcon | undefined {
  const q = query.trim().toLowerCase();
  if (!q) return undefined;
  return BRAND_ICONS.find(
    (icon) => icon.slug === q || icon.title.toLowerCase() === q,
  ) ?? BRAND_ICONS.find(
    (icon) => icon.title.toLowerCase().includes(q) || q.includes(icon.slug),
  );
}
`;

const outPath = resolve(__dirname, '../src/constants/brandIcons.ts');
writeFileSync(outPath, header);

console.log(`Wrote ${found.length} brand icons to src/constants/brandIcons.ts`);
if (missing.length) {
  console.log(
    `Skipped ${missing.length} slug(s) not present in the installed simple-icons version:`,
  );
  console.log(missing.join(', '));
}
